### ISSUE TITLE
msal.js x-frame-options deny error with custom policy AAD login

### ISSUE THREAD

**Issue by kiranbhadani** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#20] opened 2020-05-21 09:33 UTC
Error from msal - acquireTokenSilent

![image](https://user-images.githubusercontent.com/14998556/82545273-50288600-9b0b-11ea-94dd-a25d1ad7d72d.png)

**Comment by jennyf19** [comment] 2020-05-21 15:46
@derisen thoughts on this?

**Comment by derisen** [comment] 2020-05-21 19:56
@kiranbhadani could you please share your configuration for the this app (as well as the single-page app that's on the screenshot), and tell us a bit about how to replicate this? Also, what policy are you using? Anything important to mention?

**Comment by kiranbhadani** [comment] 2020-05-22 05:12
@derisen The same issue also happens with the sample app
https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp (may be I should have post issue there)

Here is my configuration
```
const apiConfig = {
  b2cScopes: ["https://sicdpstage.onmicrosoft.com/api/user_impersonation"],
  webApi: "https://localhost:49851/instance"
};
```
```
const b2cPolicies = {
    names: {
        signUpSignIn: "b2c_1a_signup_signin",
        forgotPassword: "b2c_1a_passwordreset"
    },
    authorities: {
        signUpSignIn: {
            authority: "https://sicdpstage.b2clogin.com/sicdpstage.onmicrosoft.com/B2C_1A_signup_signin",
        },
        forgotPassword: {
            authority: "https://sicdpstage.b2clogin.com/sicdpstage.onmicrosoft.com/B2C_1A_PasswordReset",
        },
    },
}
```
```
const msalConfig = {
  auth: {
    clientId: "aa....16",
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    validateAuthority: false
  },
  cache: {
    cacheLocation: "localStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false // Set this to "true" to save cache in cookies to address trusted zones limitations in IE (see: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser)
  }
};
```
you can also re-produce same issue on live site https://app.skypointcloud.com/ - just login with azure account

**Comment by derisen** [comment] 2020-05-22 16:49
Thanks a lot for the info! I couple more things to clarify:

- You are using [this sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp) as your frontend and [this sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi) as your web api?
- You are able to successfully login (judging by the the screenshot), the issue occurs when you call the web API? (however in the [link](https://app.skypointcloud.com/) you shared I got the error during login, so I'm a bit confused when it occurs)
- The error occurs with logging in with an MSA account (a personal Microsoft account, like @hotmail.com)? I was able to login and get an `id_token` with my Google account.
- You are using the `loginRedirect()` method? Does it behave the same with `loginPopup()`?
- You have registered `https://app.skypointcloud.com/callback` as a `Redirect Uri` in app registration?

Btw can you please hide your clientId in your comment above? : )

**Comment by kiranbhadani** [comment] 2020-05-23 10:26
- Yes, I am using only frontend sample, using my api instead of sample
- Yes, error is when getting access token
- Yes, login with MSA or AAD account - Works fine with local and google accounts
- Same issue with both methods
- Yes, redirect url is registered

**Comment by kiranbhadani** [comment] 2020-05-23 10:39
When using popup, note: pop gets bocked in browser
![image](https://user-images.githubusercontent.com/14998556/82728688-f6f55980-9ca6-11ea-880b-1e33ed2f2b63.png)

**Comment by derisen** [comment] 2020-05-25 15:00
Hmm, weird issue really. That fact that it only happens with Microsoft accounts and not with Local and Google accounts suggests something went wrong while setting up Microsoft as identity provider. I'll have to ask you a few more questions:

- Can you confirm that you have followed these steps [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-microsoft-account)? 
- Can you share your configuration for the API?
- In the returned response from login, you should have an `idToken` and `idTokenClaims` object. Inside the `idTokenClaims` object, there should be a claim for `tfp` (or `acr`). What is the value for it?

**Comment by kiranbhadani** [comment] 2020-05-26 13:49
* I have followed this [steps](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-multi-tenant-custom?tabs=applications), it's similar to what you have shared
* No sure, what configuration for API you want, problem is before api call
* Yes, I am getting acr with IdToken it's policy name 'b2c_1a_signup_signin'

**Comment by derisen** [comment] 2020-05-26 16:39
I'm unable to replicate this. In the screenshot you share, the error line has the url `login.microsoftonline.com/common/oauth2...`, which is weird since you are using B2C, it should be `your-website.b2clogin.com/your-policy-name/oauth2/....`. But from the configuraiton you share your `authority` string is correct so I'm not sure what is causing the call to that url.

It's also possible that your issue is similar to [this one](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1437). Could you please share your issue in the [msal.js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues)?

**Comment by kiranbhadani** [comment] 2020-05-27 05:33
@derisen I think 'login.microsoftonline.com/common/oauth2.' is called by custom policy which uses microsoft online as identity provider to enable login from any azure ad or Microsoft account (multi tenant)

https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-multi-tenant-custom?tabs=applications#add-a-claims-provider

**Comment by AWallace327** [comment] 2020-06-02 12:11
@derisen I am having exactly the same issue here.

I followed all steps here: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/README.md and here: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/README.md to set up the app and it worked fine without any issues.

I then set up a custom policy with B2C using this guide here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started, which also worked fine.

Finally I followed this guide to add Azure AD as an identity provider: https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-multi-tenant-custom?tabs=applications#add-a-claims-provider

With other identity providers the `acquireTokenSilent` call succeeds, however when a user logs in using Azure AD as the identity provider then the `acquireTokenSilent` method fails with the error described above.

With the working providers, the request made by `acquireTokenSilent` gives a 302 response with the location being the redirect URI and the access token included in it, however for the AAD provider the response is a 302 still but the location is `login.microsoftonline.com/common/oauth2...` which then causes the iframe error.

**Comment by derisen** [comment] 2020-06-03 00:27
@kiranbhadani @AWallace327 the documentation might need a fix. I'll check this with some B2C service people and get back to you when I have something.

**Comment by jennyf19** [comment] 2020-06-03 23:45
@JasSuri can you provide some insight here? thank you.

**Comment by JasSuri** [comment] 2020-06-04 09:32
Is this working in incognito browser? Usually this happens when you have multiple accounts signed in at MSA or AAD identity provider, and the silent token call iframe gets blocked since the IdP will display an account selection screen. You can test the behavior by replaying the silent token URL in another tab to see what "screen" is causing the issue.

**Comment by AWallace327** [comment] 2020-06-04 09:38
@JasSuri This is still happening for me when I am signed in to only one account or when using incognito mode.

Also, the issue does not occur when using the built in sign up/sign in flow with the built in Microsoft identity provider. It is only occurring for me when using a custom policy configured for multi-tenant login so I think the issue is specific to B2C rather than Microsoft identity provider in general.

**Comment by JasSuri** [comment] 2020-06-04 09:41
Capture the link from the Chrome network trace and open it in a new tab in the same browser window. See if you are getting stopped at some page, or given some error, or are issued a token.

Also giving us the full link here might help, since thats the one that is not returning a 302 and thus getting block (as per design).

> however for the AAD provider the response is a 302 still but the location is login.microsoftonline.com/common/oauth2...

**Comment by kiranbhadani** [comment] 2020-06-04 10:32
@JasSuri It's same for me even in chrome incognito, the url that fails is 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=xxxxxxxxxx&redirect_uri=https%3a%2f%2fsicdpstage.b2clogin.com%2fsicdpstage.onmicrosoft.com%2foauth2%2fauthresp&response_type=code&scope=openid+profile&response_mode=form_post&nonce=xxxxxxx&state=StateProperties%3xxxxxxxxxxxx'

opening this in new tab, stop on with 'Bad request'
https://sicdpstage.b2clogin.com/sicdpstage.onmicrosoft.com/oauth2/authresp

it's a post call with formdata, including code, state and session_state

**Comment by kiranbhadani** [comment] 2020-06-10 04:15
@JasSuri Any update on this? I am facing same issue with Google provider also when multiple accounts logged in

**Comment by JasSuri** [comment] 2020-06-10 09:43
I haven't been able to reproduce this on my end, at least with the single AAD tenant federation, it might be better to open a support ticket to help directly. 

I will need to check with multi tenant /common scenario as detailed in this issue.

In terms of the issue with multi account selection screens, my idea has been to pass in the email as "login_hint" to MSALs silent token call. Then in the federated IdP technical profile add an input_claim in the technical profile which passes the login_hint using a [claims resolver](https://docs.microsoft.com/en-us/azure/active-directory-b2c/claim-resolver-overview#openid-connect). Then the federated provider should skip the account selection screen. See this too: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1269

**Comment by derisen** [comment] 2020-06-22 20:31
@kiranbhadani @AWallace327 Just an update, you should be able to use [MSAL 2.x](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser) with auth code flow for B2C single page app. Since MSAL.js 2.x does not use iframes, it might perhaps help you avoid this issue.

**Comment by kiranbhadani** [comment] 2020-06-23 04:54
@derisen Yes, it would help but I think it's still not supported for B2C tenant
"Important: MSAL.js 2.0 with Authorization Code Flow is not yet available for B2C tenants"

**Comment by derisen** [comment] 2020-06-23 19:53
@kiranbhadani it's supported now (as of v2.0.0-beta.2), but needs a CORS-disabled browser for the moment to run properly. In a few weeks it will be fully supported when v2.0 comes out of beta.

**Comment by derisen** [comment] 2020-10-24 01:38
@kiranbhadani @AWallace327 MSAL.js 2.x with auth code flow now fully supports B2C. You can find the new sample [here](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa). Hope this helps.

**Comment by derisen** [comment] 2020-11-13 12:59
Closing, as this should not be an issue in 2.x. Please let us know if your problem persists.

**Closed as completed by derisen** 2020-11-13 12:59 UTC
Labels: requires more info
