### ISSUE TITLE
Unable to fetch metadata

### ISSUE THREAD

**Issue by Nikko-Foti** [Azure-Samples/active-directory-b2c-javascript-nodejs-webapi#3] opened 2017-09-20 00:12 UTC
Hi,

I am working on configuring passport-azure-ad to verify a JWT that is being send via a front-end service to my API. Unfortunately, I keep getting these errors:

Cannot get AAD Federation metadata from endpoint you specified https: ...

AND

authentication failed due to: In loadMetadata: Unable to fetch metadata

I followed the example here very closely and am using the exact BearerStrategy configuration options that were provided to me. 

Has anyone else had this error?

**Comment by ed-parry** [comment] 2018-01-14 21:30
I'm coming up against the same issues - did you manage to get anywhere with them @Nikko-Foti?

**Comment by lovemaths** [comment] 2018-01-15 01:25
@Nikko-Foti @ed-parry Can you add one line to log the error after [line 520 of bearstrategy.js](https://github.com/AzureAD/passport-azure-ad/blob/dev/lib/bearerstrategy.js#L520)? For example something like `console.log(fetchMetadataError)` and let me the error message?

**Comment by HofmT** [comment] 2018-01-18 10:29
Hey guys,

I also had the _Unable to fetch metadata_ Error. In my case it was due to the enterprise proxies. However I haven't found a solution yet to avoid it. Hope that helps you.

**Comment by danistrebel** [comment] 2018-07-11 13:30
I just ran into this thread because I had the same error in my logs. For me, the resolution was to make sure the policy name aligned with the one I defined in the Azure portal.

**Comment by TheHanna** [comment] 2019-02-28 22:38
I'm running into this problem as well, but with the OIDCStrategy. My policy name aligns. It's not a proxy issue like @HofmT, I've tried on multiple networks. I'm using a B2C tenant.

**Comment by ramitmittal** [comment] 2019-06-28 09:46
What's the policy name ? I ran into the same problem.
Ensure that the policy name starts with
b2c_1_
in lowercase only. The rest may be mixed case.

**Comment by mattschroed** [comment] 2019-07-16 18:05
If you're following the documentation here(https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp), and you're like me and follow the docs completely you'll get this error.

The problem is in the //TODO: Update the first 3 variables section.  The documentation tells you to change:
var tenantID = "<your-tenant-name>.onmicrosoft.com";
var clientID = "<Application ID for your Node.js Web API - found on Properties page in Azure portal>";
var policyName = "<Name of your sign in / sign up policy, e.g. B2C_1_SiUpIn>";

It doesn't mention the line above those 3 which has tenantName which you have to modify and ignore the tenantID = your-tenant-name.onmicrosoft.com portion in the docs, just leave it how it is and add your tenant name to the tenantName var or delete the tenantName + value.

**Comment by jennyf19** [comment] 2020-02-06 17:17
@Nikko-Foti @ed-parry @HofmT @danistrebel @mattschroed This sample should be working consistently now.

**Comment by derisen** [comment] 2020-03-04 23:30
Issue is resolved. Closing this.

**Closed as completed by derisen** 2020-03-04 23:30 UTC

**Comment by ChamseddineBhd** [comment] 2020-03-12 09:37
Hello, I have the same issue !!  what should i do !!  i have verified all params !
 404 Cannot get AAD Federation metadata ...

**Comment by derisen** [comment] 2020-03-12 23:53
Hi @ChamseddineBhd , can you please give more details. Are you using the most recent version of the sample? Can you paste your config.js file here (masking the sensitive information)? thanks

**Comment by DarkLite1** [comment] 2020-07-06 07:31
Having the same issue, upon app start all is fine and no error is displayed:
```
{"name":"AzureAD: Bearer Strategy","hostname":"BELSGFRANIT04","pid":1900,"level":40,"msg":"Production environments should always validate the issuer.","time":"2020-07-06T07:27:08.881Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"BELSGFRANIT04","pid":1900,"level":30,"msg":"In BearerStrategy constructor: strategy created","time":"2020-07-06T07:27:08.883Z","v":0}
Listening on port 5000
```

Then when visiting the protected route http://localhost:5000/hello with the brwoser (unauthorized) we get this:
```
{"name":"AzureAD: Metadata Parser","hostname":"BELSGFRANIT04","pid":1900,"level":50,"msg":"cannot get AAD Federation metadata from endpoint you specified","time":"2020-07-06T07:29:08.102Z","v":0}
{"name":"AzureAD: Metadata Parser","hostname":"BELSGFRANIT04","pid":1900,"level":50,"msg":"cannot get AAD Federation metadata from endpoint you specified","time":"2020-07-06T07:29:08.102Z","v":0}
{"name":"AzureAD: Bearer Strategy","hostname":"BELSGFRANIT04","pid":1900,"level":30,"msg":"authentication failed due to: Error: Cannot get AAD Federation metadata","time":"2020-07-06T07:29:08.104Z","v":0}
GET /hello 401 163.631 ms - -
```

This happens with the latest sample.

**Comment by alexkrytsky** [comment] 2021-01-29 20:10
Hello, I had the same issue. The thing that solved it for me, in the identityMetadata, instead of using https://login.microsoftonline.com/your_tenant_name**.onmicrosoft.com**/v2.0/.well-known/openid-configuration
use same string but without **.onmicrosoft.com**

**Comment by derisen** [comment] 2021-01-29 21:14
@alexkrytsky thank you very much for catching this. that's correct. We'll fix that asap

**Comment by derisen** [comment] 2021-01-29 21:24
@alexkrytsky this string (identityMetadata) should match the **Azure AD B2C OpenID Connect Metadata document** in your **App registration > Endpoints** tab

![screenshot](https://user-images.githubusercontent.com/13197548/106328726-2ba5b180-6235-11eb-9482-a019cb6c9c4f.png)

In **config.js**, if you have only entered the name of your tenant (without _.onmicrosoft.com_), it should work as intended. But feel free to open a new issue and share your app config there.

**Comment by alexkrytsky** [comment] 2021-01-29 21:26
I have another issue that I'm trying to resolve with "passport-azure-ad".
Would it be okay to ask over this thread?

~Alex
